config/routes.rb
Rails.application.routes.draw do
  resources :blogs
  resources :games
  devise_for :users, controllers: { sessions: 'users/sessions' }
  resources :pages

  root to: 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/_form.html.erb
<%= form_for(page) do |f| %>
  <% if page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :home %>
    <%= f.text_field :home %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<p id="notice"><%= notice %></p>
<div class="col">
<div class="row">
<center>
<h1>Esports Data Visualisation</h1><br>
</center>
<center>
<%= image_tag('Esportslogo.png', width: '78%', height: '240px') %>

<p><br><br>SharkTank Esports visualisation. Your #101th source for League of Legends Data. </p>
<div class="col-xs-5">
<table>
<thead><h1>News</h1></thead>

<tbody>
<p>Hi! This is the news section for the second worst ESports Data visualiser. We are live and ready to roll - keep a look out for more news.</p>
</tbody>
</table>
</div>
<!--
<table>
  <thead>
    <tr>
      <th>Home</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= page.home %></td>
        <td><%= link_to 'Show', page %></td>
        <td><%= link_to 'Edit', edit_page_path(page) %></td>
        <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Page', new_page_path %>

-->
</center>
</div>
</div>

app/views/pages/new.html.erb
<h1>New Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Home:</strong>
  <%= @page.home %>
</p>

<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>